package com.example.demo.service;

import com.example.demo.model.User;
import com.example.demo.repository.UserRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.Optional;

@Service
public class DemoServices {

    @Autowired
    private UserRepository userRepository;

    @Autowired
    private PasswordEncoder passwordEncoder;

    public String getServiceMessage() {
        return "This is a message from the DemoServices class.";
    }

    public Object getComplexData() {
        // Emulator random complex data generation
        Map<String, Object> complexData = new HashMap<>();
        complexData.put("name", "Complex Data");
        complexData.put("value", 42);
        complexData.put("description", "This is some complex data generated by the service.");

        return complexData;
    }

    // CRUD Operations for User

    // Create
    public User createUser(User user) {
        if (user.getPassword() != null && !user.getPassword().isBlank()) {
            user.setPassword(passwordEncoder.encode(user.getPassword()));
        }

        if (user.getRole() == null || user.getRole().isBlank()) {
            user.setRole("USER");
        }

        return userRepository.save(user);
    }

    // Read - Get all users
    public List<User> getAllUsers() {
        return userRepository.findAll();
    }

    // Read - Get user by ID
    public Optional<User> getUserById(Long id) {
        return userRepository.findById(id);
    }

    // Read - Get users by name
    public List<User> getUsersByName(String name) {
        return userRepository.findByName(name);
    }

    // Read - Get user by email
    public Optional<User> getUserByEmail(String email) {
        return userRepository.findByEmail(email);
    }

    // Update
    public User updateUser(Long id, User userDetails) {
        Optional<User> optionalUser = userRepository.findById(id);
        if (optionalUser.isPresent()) {
            User user = optionalUser.get();
            user.setName(userDetails.getName());
            user.setEmail(userDetails.getEmail());
            user.setAge(userDetails.getAge());

            if (userDetails.getPassword() != null && !userDetails.getPassword().isBlank()) {
                user.setPassword(passwordEncoder.encode(userDetails.getPassword()));
            }

            if (userDetails.getRole() != null && !userDetails.getRole().isBlank()) {
                user.setRole(userDetails.getRole());
            }

            return userRepository.save(user);
        }
        return null;
    }

    // Delete
    public boolean deleteUser(Long id) {
        if (userRepository.existsById(id)) {
            userRepository.deleteById(id);
            return true;
        }
        return false;
    }

    // Initialize demo data
    public void initializeDemoData() {
        // if (userRepository.count() == 0) {
        userRepository.save(new User("John Doe", "john@example.com", 30, passwordEncoder.encode("123456"), "USER"));
        userRepository.save(new User("Jane Smith", "jane@example.com", 25, passwordEncoder.encode("123456"), "USER"));
        userRepository.save(new User("Bob Johnson", "bob@example.com", 35, passwordEncoder.encode("123456"), "ADMIN"));
        // }
    }
}
